#%RAML 1.0 Trait
 responses:
    201:
      body:
        application/json:
          example:
            {"result":"Created"}
    202:
      body:
        application/json:
          example:
            {"accepted"}
    203:
      body:
        application/json:
          example:
            {"N0n-Authoritative information"}  