#%RAML 1.0 Trait
 responses:
   200:
     body:
        application/json:
          example:
            {"remove bill data"}
   403:
     body:
        application/json:
          example:
            {"Forbidden"}
   404:
     body:
        application/json:
          example:
            {"Not Found"}
   405:
     body:
        application/json:
          example:
            {"Method Not Allowed"} 
   