#%RAML 1.0 Trait
responses:
  200:
    body:
      application/json:
        example: {"ok"}
  203:
    body:
      application/json:
        example:
          {"Non-Authoritative Information"} 
  204:
    body:
      application/json:
        example:
          {"No content"} 