#%RAML 1.0 Trait
 responses:
    200:
      body:
        application/json:
          example:
            {"ok"}
    404:
      body:
        application/json:
          example:
            {"not found"}  