#%RAML 1.0 Trait
responses:
  200:
    body:
      application/json:
        example: {"id":"","name":"","rate":"","barecode":""}
         
  201:
    body:
      application/json:
        example:
           [{"id":" ","name":"",}] 
