#%RAML 1.0 Trait
responses:
  202:
    body:
      application/json:
        example:
          {"Accepted"}
  203:
    body:
      application/json:
        example:
          {" Non-Authoritative Information"}