#%RAML 1.0 Trait
responses:
  200:
    body:
      application/json:
        example:
          [{name="id", type="int"},
 {name="name" ,type="string"},
 {name="barcode" ,type="string"},
 {name="rate" ,type="double"},
{name="productCategory" ,type="string",}]  
