#%RAML 1.0 Trait
responses:
  200:
    body:
      application/json:
        example:
          {"updeate"}

  500:
    body:
      application/json:
        example:
          {"Internal Server Error"}
  501:
    body:
      application/json:
        example: {"Not Implemented"}
  400:
    body:
      application/json:
        example:
          {"Bad Gateway"}  
  503:
    body:
      application/json:
        example:
          {"Service Unavailable"} 
