#%RAML 1.0 Trait
responses:
  200:
    body:
      application/json:
        example:
          [{ "id" : integet},
          {"name" : noOfItems},
          {"totalCost" : integer},
          {"totalValue" : integer}
          ]
  304:
    body:
      application/json:
        example:
          {"Error":"Not Modified"} 